# Use the official Python image as the base image
FROM python:3.12.2-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the application code into the container
COPY . .

# Install uv
RUN pip install uv

# Create a virtual environment and sync dependencies using uv
RUN uv venv
RUN uv sync

# Expose the port Streamlit runs on
EXPOSE 8501

# Set environment variables for Streamlit
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

# Command to run the Streamlit application
ENTRYPOINT [".venv/bin/streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
